Add 8.0.1 release notes for Fleet and Elastic Agent
elastic/observability-docs pull request #1601
Opened 2022-02-18 01:23 UTC by dedemorton

Adds release notes for 8.0.1.

2022-02-18 01:23 UTC, apmmachine commented
A documentation preview will be available soon:</br><ul><li>📚 [HTML diff](https://observability-docs_1601.docs-preview.app.elstc.co/diff)</li><li>📘 [Fleet and Elastic Agent Guide](https://observability-docs_1601.docs-preview.app.elstc.co/guide/en/fleet/master/index.html)</li><li>📙 [Observability Guide](https://observability-docs_1601.docs-preview.app.elstc.co/guide/en/observability/master/index.html)</li></ui>
<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-21 13:43 UTC, ph requested changes

2022-02-21 13:43 UTC, ph commented on docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
> +being removed and downloaded again. {agent-pull}30281[#30281]
This is not part of 8.0.1

2022-02-22 19:09 UTC, jen-huang approved these changes
Fleet LGTM

2022-02-22 19:53 UTC, dedemorton commented on docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
> +being removed and downloaded again. {agent-pull}30281[#30281]
```suggestion
```

2022-02-22 19:54 UTC, dedemorton commented on docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
> +// begin 8.0.1 relnotes
```suggestion
// begin 8.0.0 relnotes
```

2022-02-22 20:44 UTC, ph approved these changes

2022-02-22 20:44 UTC, ph commented
LGTM thanks @dedemorton

2022-02-22 22:04 UTC, merged