add observer.geo.name for maps and machine learning
elastic/observability-docs pull request #171
Opened 2020-10-07 19:07 UTC by DanRoscigno

Same change as to the Heartbeat docs

2020-10-07 19:07 UTC, apmmachine commented
A docs preview will be available soon: </br> - [HTML diff](https://observability-docs_171.docs-preview.app.elstc.co/diff) </br> - [Observability guide](https://observability-docs_171.docs-preview.app.elstc.co/guide/en/observability/master/index.html)
<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-10-08 13:08 UTC, EamonnTP requested changes
Couple of minor suggestions.

2020-10-08 13:08 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +[[configurelocation]]
```suggestion
[[configure-heartbeat-location]]
```

2020-10-08 13:08 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +=== Step 4: Configure the Heartbeat location
```suggestion
== Step 4: Configure {beatname_uc} location
```

2020-10-08 13:08 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +Heartbeat can be deployed in multiple locations so that you can detect
```suggestion
{beatname_uc} can be deployed in multiple locations so that you can detect 
```

2020-10-08 13:08 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +Configure the Heartbeat location to allow {kib} to display location-specific
```suggestion
Configure the {beatname_uc} location to allow {kib} to display location-specific
```

2020-10-08 13:08 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +To configure the location of a Heartbeat instance, modify the
```suggestion
To configure the location of a {beatname_uc} instance, modify the 
```

2020-10-08 13:45 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +[float]
You can remove this float attribute.

2020-10-08 13:45 UTC, EamonnTP commented on docs/en/observability/ingest-uptime.asciidoc
> +[float]
You can remove this float attribute.

2020-10-08 14:05 UTC, DanRoscigno commented on docs/en/observability/ingest-uptime.asciidoc
> +[float]
done

2020-10-08 14:06 UTC, DanRoscigno commented on docs/en/observability/ingest-uptime.asciidoc
> +[float]
done

2020-10-13 13:59 UTC, EamonnTP approved these changes

2020-10-13 15:51 UTC, merged