Add Fleet/Agent release notes for 7.17.2
elastic/observability-docs pull request #1737
Opened 2022-03-30 20:23 UTC by dedemorton

Adds release notes for 7.17.2 and fixes commented out template.

2022-03-30 20:38 UTC, jen-huang approved these changes
Fleet LGTM

2022-03-31 12:56 UTC, ph requested changes
We are missing this important commit

Fix the start sequence of beats that was non-deterministic making beats missing their configuration from Agent and not sending events.

https://github.com/elastic/beats/pull/30694

2022-03-31 13:10 UTC, ph commented on docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
> +* Fix the start sequence of beats that was non-deterministic making beats missing their
👍🏽

2022-03-31 13:11 UTC, ph commented
LGTM, I will check the 8.1.2, if this entry is missing too.

2022-03-31 13:22 UTC, merged