[DOCS] Adds note on how to update custom rules of Metric anomaly jobs
elastic/observability-docs pull request #249
Opened 2020-11-13 13:49 UTC by szabosteve

## Overview

This PR adds a note to the `Inspect metric anomalies` page about how to update the custom rules of a pre-configured Metric anomaly detection job.

### Preview

[Inspect metric anomalies]()

2020-11-13 14:42 UTC, szabosteve commented
@elasticmachine test this please

2020-11-16 08:10 UTC, apmmachine commented
A docs preview will be available soon: </br> - [HTML diff](https://observability-docs_249.docs-preview.app.elstc.co/diff) </br> - [Observability guide](https://observability-docs_249.docs-preview.app.elstc.co/guide/en/observability/master/index.html)
<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-11-16 09:27 UTC, EamonnTP requested changes
Looks good! Just a minor suggestion.

2020-11-16 09:27 UTC, EamonnTP commented on docs/en/observability/inspect-metric-anomalies.asciidoc
> +rules* option under *actions*. The changes take effect for new results only. If
```suggestion
These pre-defined {anomaly-jobs} use {ml-docs}/ml-rules.html[custom rules]. To
update the rules in the *Anomaly Explorer*, select *actions > Configure 
rules*. The changes only take effect for new results.
```

2020-11-16 10:20 UTC, szabosteve commented
Thanks @EamonnTP, I addressed your comment via 996cf49

2020-11-16 11:07 UTC, EamonnTP commented on docs/en/observability/inspect-metric-anomalies.asciidoc
> +you want to apply the changes to existing results, clone and rerun the job.
```suggestion
If you want to apply the changes to existing results, clone and rerun the job.
```

2020-11-16 11:21 UTC, szabosteve commented
@EamonnTP Thanks!

2020-11-16 11:27 UTC, EamonnTP approved these changes

2020-11-16 11:32 UTC, merged