Update permissions for synthetics getting started
elastic/observability-docs pull request #2645
Opened 2023-02-15 13:00 UTC by shahzad31

2023-02-16 15:09 UTC, dominiqueclarke commented on docs/en/observability/synthetics-get-started-ui.asciidoc
> +* {ref}/security-privileges.html#privileges-list-indices[Indices privileges] for `synthetics-*`: `read`, `view_index_metadata`, `create_doc`, `auto_configure` and for `.alerts-observability.uptime.al
We should probably also add Kibana `Synthetics and Uptime` all permissions.

2023-02-16 20:03 UTC, colleenmcginnis approved these changes
👍  If you add more permissions per @dominiqueclarke's comment, you can verify it is formatted correctly using [this preview link](https://observability-docs_2645.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-get-started-ui.html#uptime-set-up-prereq) (it will take several minutes for the preview to build).

2023-02-20 16:14 UTC, paulb-elastic commented
Been discussing / testing with others in the team and the updated permissions are not enough for Private Locations that fail with just these (missing Fleet permissions).  Would be good to add the additional permissions needed to the [Private Locations docs page](https://www.elastic.co/guide/en/observability/current/synthetics-private-location.html#monitor-via-private-agent)

2023-02-22 21:30 UTC, dominiqueclarke requested changes
I just want to point out that these original permissions were created with the express purpose of describing the permission set needed to _enable_ synthetics. That is, the permission set needed to generate an api key that can be used by the service.

That is why there is a miss of Kibana permissions on here, as well as Fleet permissions for private locations. Both are irrelevant for generating the api key needed for Synthetics. 

That being said, it is clear that these docs are confusing, I'm just wondering what the right route to go here is. An admin needed to enable Synthetics and generate the api key needs a higher permission set than the average user. 

I want to distinguish between admins and Synthetics users. I'm not sure what is the best, clearest way to do so. @colleenmcginnis 

I don't necessarily want to lump all the permissions needs to use Synthetics as a user here, because I don't wnat to make it seem like ordinary synthetics users need cluster advanced cluster permissions.

Admin (Needed to generate the synthetics service api key for public locations)
```
* {ref}/security-privileges.html#privileges-list-cluster[Cluster privileges]: `monitor`, `read_ilm`, `read_pipeline`, and at least one of `manage_own_api_key`, `manage_security`, or `manage_api_key`
* {ref}/security-privileges.html#privileges-list-indices[Indices privileges] for `synthetics-*`: `read`, `view_index_metadata`, `create_doc`, `auto_configure`
* Kibana privileges: Synthetics/Uptime ALL
```

Uptime write user using private locations
```
* {ref}/security-privileges.html#privileges-list-indices[Indices privileges] for `synthetics-*`: `read` and for `.alerts-observability.uptime.alerts-*`: `read`
* Kibana privileges: Uptime/Synthetics: All, Fleet: All, Integrations: All
```


Uptime write user NOT using private locations
```
* {ref}/security-privileges.html#privileges-list-indices[Indices privileges] for `synthetics-*`: `read` and for `.alerts-observability.uptime.alerts-*`: `read`
* Kibana privileges: Uptime/Synthetics
```

AND if users want to use project monitors, they'll need
```
* {ref}/security-privileges.html#privileges-list-cluster[Cluster privileges]: At least one of `manage_own_api_key`, `manage_security`, or `manage_api_key`
```

2023-02-24 12:44 UTC, paulb-elastic commented
To add to this, https://github.com/elastic/observability-docs/issues/2707 has been raised for the _use_ of Synthetics (as opposed to enabling MM)

2023-04-04 16:32 UTC, closed without merging