Metrics app alerts: 7.12 updates
elastic/observability-docs pull request #404
Opened 2021-02-24 10:34 UTC by EamonnTP

### Summary

This PR adds alerting content for the Metrics app 7.12 docs release. Along with minor edits, included is content for:

- Infrastructure anomaly alert
- Severity levels for the Infrastructure threshold alert and the Metrics threshold alert

### HTML preview

Coming soon...

### Related issues

Closes https://github.com/elastic/observability-docs/issues/275
Closes https://github.com/elastic/observability-docs/issues/384

2021-02-24 10:35 UTC, apmmachine commented
A docs preview will be available soon: </br> - [HTML diff](https://observability-docs_404.docs-preview.app.elstc.co/diff) </br> - [Observability guide](https://observability-docs_404.docs-preview.app.elstc.co/guide/en/observability/master/index.html)
<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-02-25 10:07 UTC, sorantis requested changes
@EamonnTP the docs look good. 
For the parts of docs where warning and critical are mention can we also add some information about alert actions? Namely, the expand on the options provided in "Run When"?
<img width="569" alt="Screen Shot 2021-02-25 at 11 07 01" src="https://user-images.githubusercontent.com/1685068/109137603-aa6d0c00-7759-11eb-9bf4-267972b92707.png">

2021-02-25 12:58 UTC, EamonnTP commented
Thanks @sorantis I added the relevant content.

2021-02-25 13:00 UTC, sorantis approved these changes

2021-02-25 15:55 UTC, bmorelli25 approved these changes
👍 Lookin' good

2021-02-25 15:59 UTC, merged