Added docs for capabilities
elastic/observability-docs pull request #422
Opened 2021-03-03 12:10 UTC by michalpristas

2021-03-03 12:11 UTC, apmmachine commented
A docs preview will be available soon: </br> - [HTML diff](https://observability-docs_422.docs-preview.app.elstc.co/diff) </br> - [Observability guide](https://observability-docs_422.docs-preview.app.elstc.co/guide/en/observability/master/index.html)
<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-03-08 14:47 UTC, EamonnTP requested changes
@michalpristas Many thanks for these updates. Just a few minor suggestions from me. Could you double check to ensure that the indentations are correct in the yaml file examples? Thanks again!

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +**Supported capabilites:**
```suggestion
[supported-capabilities]
=== Supported capabilities
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +Capabilities can be used to alter congestion of outputs, inputs or upgrade capability of agent.
```suggestion
You can use capabilities to modify the congestion of outputs, inputs or upgrade the capability of {agent}.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +For inputs we use `input` key as follows containing an expression:
```suggestion
[capabilities-inputs]
==== Inputs

For inputs, you can the `input` key containing an expression.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +For outputs we use `output` key as follows containing an expression:
```suggestion
[capabilities-outputs]
==== Outputs

For outputs, you can use the `output` key containing an expression.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +For upgrade we use `output` key as follows containing an expression allowing upgrade just to version `8.0.0`:
```suggestion
[capabilities-upgrade]
==== Upgrade

For an upgrade, you can use the `output` key containing an expression that allows a specific upgrade to version `8.0.0`. `${version}` is the target version.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +where `${version}` is a target version.
This can be removed as we addressed in the previous comment.
```suggestion
where `${version}` is a target version.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +With version EQL conditions can be used as well as `*` wildcard:
```suggestion
With a versioned EQL, conditions can be used, as well as a * wildcard. This allows upgrades just for bug fixes.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +allows upgrades just for bug fixes.
This can be removed as we addressed in the previous comment. 
```suggestion
allows upgrades just for bug fixes.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +Upgrade capability definition:
```suggestion
**Upgrade capability definition**

This upgrade definition allows upgrades just for minor version changes.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +Allows upgrades just for minor version change.
This can be removed as we addressed it in the previous comment.

```suggestion
Allows upgrades just for minor version change.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +downloading.
```suggestion
Part of the upgrade action is also a `source_uri` address that specifies the repository from where artifacts should be
downloaded.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +To restrict only to https only we could use:
```suggestion
To restrict to HTTPS, you can use the following.
```

2021-03-08 14:47 UTC, EamonnTP commented on docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
> +Upgrade capability is blocking. This means that in case action does not meet first upgrade definition, we're not proceeding with evaluation.
```suggestion
In the example above, upgrade capability is blocked. If the action does not meet the first definition, the upgrade is prevented.
```

2021-03-10 19:29 UTC, dedemorton commented
Thanks for reviewing this, Eamonn! I owe you one. (Removing my name from the reviewer list since Eamonn has graciously stepped up to help.)

2021-03-16 14:08 UTC, EamonnTP commented
Hi @michalpristas This PR can now be merged and also back ported to the 7.x and 7.12 branches. If you would like any help in doing this, please let me know. Thanks.

2021-03-16 14:10 UTC, merged